image: ruby:2.3

pages:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build blog_bkdev_me.gemspec
  artifacts:
    paths:
    - public
    - "blog_bkdev_me-*.gem"
  only:
  - master
