# Site settings
title: Quoc Khanh Developer
# subtitle:
email: bkdev98@gmail.com
description: I'm a Developer making the web an awesome place.<br /> And I love to write.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.bkdev.me" # the base hostname & protocol for your site
author: bkdev
street_address: Dist 12.
city: Ho Chi Minh City
state: HCM
zip_code: 69696
country: Vietnam
phone: (84) 917 679 524

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://fb.com/bkdev98
github_url: https://github.com/bkdev98
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/bkdev98
linkedin_url: https://www.linkedin.com/in/bkdev98
pinterest_url:
slack_url: https://fptdev.slack.com
twitter_url: https://twitter.com/bqkhanh98

# Build settings
markdown: kramdown
